[i18n-kit] app-i18n/ibus Pin app-i18n/ibus version to 1.5.31
Set the ibus version explicitly to 1.5.31 in the autogen.yaml file as the 1.5.32 fails with undefined reference to g_variant_builder_init_static` and later on wayland client functionality

(cherry picked from commit 3f6474ea57d92829bfb38749545eeeac358082a0)